version: '3.8'

services:
  postgres-db:
    # image: postgres:13
    # ports:
    #   - 5434:5432
    # environment:
    #   POSTGRES_USER: postgres   # ENV
    #   POSTGRES_PASSWORD: 123    # ENV
    #   POSTGRES_DB: nest         # ENV
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - transcendence
  monorepo:
    build:
      context: ./monorepo
      dockerfile: Dockerfile
    volumes:
      - ./monorepo:/app/monorepo
    ports:
      - "3000:3000"
      # - "5555:5555"  # for prisma studio
    # env_file: .env
    depends_on:
      - postgres-db
    networks:
      - transcendence

networks:
  transcendence:
