version: '3.8'

services:
  postgres-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .env
    # volumes:
    #   - ./db/data:/var/lib/postgresql/data
    networks:
      - transcendence
  monorepo:
    build:
      context: ./monorepo
      dockerfile: Dockerfile
    volumes:
      - ./monorepo:/app/monorepo
    ports:
      - "3000:3000"
      # - "5555:5555"  # for prisma studio
    # env_file: .env
    depends_on:
      - postgres-db
    networks:
      - transcendence

networks:
  transcendence:
