version: '3.8'

services:
  postgres-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - transcendence
  monorepo:
    build:
      context: ./monorepo
      dockerfile: Dockerfile
    volumes:
      - ./:/app/monorepo
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    networks:
      - transcendence

networks:
  transcendence:
